import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
import Header from "./compunet/header.js";
import Ticker from './compunet/Ticker';
export const metadata = {
  title: " موقع تركي النهدي",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const athkar = [
    "سبحان الله",
    "الحمد لله",
    "لا إله إلا الله",
    "الله أكبر",
    "لا حول ولا قوة إلا بالله",
    "سبحان الله وبحمده",
    "سبحان الله العظيم",
    "أستغفر الله",
    "الحمد لله الذي بنعمته تتم الصالحات",
    "اللهم صلِّ على محمد"
];
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Ticker textList={athkar}   /> {/*   هذا الاستدعاء حق الشريط من الصفحة حقه */}
        {children}
      </body>
    </html>
  );
}
